### ISSUE TITLE
ToggleUI breaks when number of keyboards changes from 2 to 1.

### ISSUE THREAD

**Issue by Sethyboy0** [keymanapp/keymanweb#58]
When using the KeymanWeb ToggleUI, removing a keyboard with a call to KeymanWeb.removeKeyboards() while exactly 2 keyboards are loaded causes the ToggleUI to break. From what I've looked at when doKeyboardUnregistered is called the event handler for ToggleUI doesn't remove the removed keyboard from its internal keyboard array. This then leads to all kinds of issues when it attempts to switch the button back into single course mode.

**Comment by mcdurdin** [comment]
Tested and appears to be working. Cannot remove last keyboard but that's different.
